### ISSUE TITLE
IOError: [Errno 9] Bad file descriptor

### ISSUE THREAD

**Issue by leominov** [worthwhile/fabric-bolt#139]
This error makes me cry:
```
Executing task 'test' 
{'disable_known_hosts': False, 'skip_bad_hosts': False, 'linewise': False, 'show': None, 'key_filename': None, 'abort_on_prompts': False, 'system_known_hosts': None, 'reject_unknown_hosts': False, 'tasks': ['test'], 'roledefs': {}, 'gateway': None, 'connection_attempts': 1, 'keepalive': 0, 'eagerly_disconnect': False, 'rcfile': '/root/.fabricrc', 'password': None, 'hide': None, 'sudo_prefix': "sudo -S -p '%(sudo_prompt)s' ", 'lcwd': '', 'no_agent': False, 'forward_agent': False, 'ROOT_PATH': '/raid/www/platform.arm', 'port': '22', 'ok_ret_codes': [0], 'version': '1.8.1', 'use_exceptions_for': {'network': False}, 'hosts': ['aminov.dev.weburg.ru'], 'command_prefixes': [], 'new_style_tasks': False, 'cwd': '', 'abort_exception': None, 'real_fabfile': '/usr/local/lib/python2.7/dist-packages/fabric_bolt/fabfile.py', 'passwords': {}, 'shell': '/bin/sh -c', 'BRANCH': 'feature/DIR.I5.2.3-327', 'shell_env': {}, 'always_use_pty': True, 'colorize_errors': False, 'default_port': '22', 'all_hosts': ['aminov.dev.weburg.ru'], 'local_user': 'root', 'again_prompt': 'Sorry, try again.', 'echo_stdin': True, 'use_ssh_config': False, 'command_timeout': None, 'path': '', 'path_behavior': 'append', 'combine_stderr': True, 'host_string': 'aminov.dev.weburg.ru', 'dedupe_hosts': True, 'warn_only': False, 'sudo_prompt': 'sudo password:', 'no_keys': False, 'roles': [], 'fabfile': '/usr/local/lib/python2.7/dist-packages/fabric_bolt/fabfile.py', 'use_shell': True, 'host': 'aminov.dev.weburg.ru', 'pool_size': 0, 'remote_interrupt': None, 'output_prefix': True, 'command': 'test', 'timeout': 10, 'exclude_hosts': [], 'ssh_config_path': '~/.ssh/config', 'parallel': False, 'sudo_user': None, 'user': 'aminov'} 
[aminov.dev.weburg.ru] run: whoami 
Traceback (most recent call last): 
File "/usr/local/lib/python2.7/dist-packages/fabric/main.py", line 743, in main 
*args, **kwargs 
File "/usr/local/lib/python2.7/dist-packages/fabric/tasks.py", line 368, in execute 
multiprocessing 
File "/usr/local/lib/python2.7/dist-packages/fabric/tasks.py", line 264, in _execute 
return task.run(*args, **kwargs) 
File "/usr/local/lib/python2.7/dist-packages/fabric/tasks.py", line 171, in run 
return self.wrapped(*args, **kwargs) 
File "/usr/local/lib/python2.7/dist-packages/fabric_bolt/fabfile.py", line 9, in test 
run('whoami') 
File "/usr/local/lib/python2.7/dist-packages/fabric/network.py", line 639, in host_prompting_wrapper 
return func(*args, **kwargs) 
File "/usr/local/lib/python2.7/dist-packages/fabric/operations.py", line 1042, in run 
shell_escape=shell_escape) 
File "/usr/local/lib/python2.7/dist-packages/fabric/operations.py", line 911, in _run_command 
stderr=stderr, timeout=timeout) 
File "/usr/local/lib/python2.7/dist-packages/fabric/operations.py", line 795, in _execute 
worker.raise_if_needed() 
File "/usr/local/lib/python2.7/dist-packages/fabric/thread_handling.py", line 12, in wrapper 
callable(*args, **kwargs) 
File "/usr/local/lib/python2.7/dist-packages/fabric/io.py", line 215, in input_loop 
byte = msvcrt.getch() if win32 else sys.stdin.read(1) 
IOError: [Errno 9] Bad file descriptor 
```

Some info:

```
dev% pip freeze | grep bolt
fabric-bolt==0.0.3
```

```
dev% python --version
Python 2.7.3
```

If I run task like this:
```
from fabric.api import *

env.hosts = ['aminov@aminov.dev.weburg.ru']

env.shell = '/bin/sh -c'
env.abort_on_prompts = False

def test():
    """TEST"""
    print env
    run('whoami')
```

No error:
```
[aminov@aminov.dev.weburg.ru] run: whoami
[aminov@aminov.dev.weburg.ru] out: aminov
[aminov@aminov.dev.weburg.ru] out: 


Done.
Disconnecting from aminov@aminov.dev.weburg.ru... done.
```

Any chance to fix it?

Thanks

**Comment by leominov** [comment]
Version 0.0.3, but this block of code:
```
process = subprocess.Popen(self.build_command(), shell=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
```
not the same (https://github.com/worthwhile/fabric-bolt/blob/master/fabric_bolt/projects/views.py):
```
            process = subprocess.Popen(
                build_command(self.object, self.request.session),
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
                shell=True,
                executable=getattr(settings, 'SHELL', '/bin/sh'),
            )
```

**Comment by leominov** [comment]
Fix it by adding stdin:
```
process = subprocess.Popen(self.build_command(), shell=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, stdin=subprocess.PIPE)
```

**Comment by avra911** [comment]
I had the same problem in 0.1 version @leominov 
your fix is working, why not make a pull request with it? is this an isolated problem on just some enviroments?

R
